name: OverseerAuth
main: io.github.andyandreih.overseer.auth.OverseerAuth
version: 0.0.1-SNAPSHOT
depend: [OverseerMain]
commands:
   overseer:
      description: The main command for Overseer
      usage: /overseer [subcommand/help]
   os:
      description: The main command for Overseer
      usage: /os [subcommand/help]