name: OverseerAuth
author: AndyAndreiH
authors: [Migs84]
website: http://katgamestudios.com/
main: com.katgamestudios.andyandreih.overseer.auth.OverseerAuth
version: 0.0.1b-SNAPSHOT
depend: [OverseerMain]
database: false
commands:
   overseer:
      description: The main command for Overseer
      usage: /overseer [subcommand/help]
      aliases: os
permissions:
    overseer.auth.*:
       description: Master permission node
       children:
          overseer.auth.simulate: true
    overseer.auth.simulate:
       description: Gives access to the simulator
       default: op
