name: OverseerAuth
author: AndyAndreiH
authors: [Migs84]
website: http://katgamestudios.com/
main: com.katgamestudios.andyandreih.overseer.auth.OverseerAuth
version: 0.2.1-SNAPSHOT
depend: [OverseerMain]
database: false
commands:
   login:
      description: Logs in the user
      usage: /login <password>
   register:
      description: Registers the user
      usage: /register <password>
permissions:
   overseer.auth.*:
      description: Master permission node
      children:
         overseer.auth.simulate: true
   overseer.auth.simulate:
      description: Gives access to the simulator
      default: op
