name: OverseerAuth
main: io.github.andyandreih.overseerauth.OverseerAuth
version: 0.0.1-SNAPSHOT
depend: [SQLibrary]
commands:
   overseer:
      description: The main command for Overseer
      usage: /overseer